print("Nombre del alumno; Sharlene Miorzlava Cervantes Vazquez")
print("lugar de residencia: El refugio de Agua zarca")
print("Fecha de Nacimiento: 24 de enero del año 2002")
print("Color favorito: Verde")
print("Animal Favorito: Panda")
print("¿Que es un Programa? Es una serie de instruccionespreviamente codificadas, las cuales permitenrealizar una tarea especifica en una computadora. Ha esta serie de intrucciones previamente codificadas, se les conoce como codigo fuente")
print("¿Por que es importante la programacion? Porque gracias a ella se han desarrollado herramientas y soluciones que le han facilitado la vida al hombre, un claro ejemplo de esto es la comunicacion, tener todo a la mano.")
print("Herencia: Heredar atributos y metodos de otra clase; Jerarquias que presentan la relacion ordenada de las clases que estan relacionadas, reutilizacin de codigos o programas")
print("Poliformismo: Formas y estapas diferentes, es la habilidad de un objeto de realidar una accion de diferentes maneras utilizando metodos igual")
print("Abstraccion: Principio por el cual se descarta toda aquella informacion que no resulta relevante en un contexto en particular, entatizando algunos de las detalles o propiedades de los objetos")
print("Almecenar y orgamizar las caractersticas y funcionalidades de los objetos representadolas por medio de atribulos y metodos; garantiza la integridad de los datos que contiene un objeto, osea que los dotos sean correctos")